---
title: "Exploring Economic Mobility through Data"
author: "Andrew Doherty-Munro and Sabrina Beaver"
format:
  pdf:
    include-in-header:
      text: |
        % Enable wrapping for Pandoc code blocks in PDF
        \usepackage{fvextra}
        \usepackage{float}
        \usepackage{makecell}
        \usepackage{booktabs}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
editor: source
execute-dir: project
execute: 
    echo: true
---

Group Members: Andrew Doherty-Munro and Sabrina Beaver

Github Usernames: adohertymunro and sabtriestech

Section: Monday 10:30 (Section 2)

```{python}
#| echo: false
#| output: false
# setup
import geopandas as gpd
from pathlib import Path
import os
import pandas as pd
import numpy as np
import altair as alt
import matplotlib.pyplot as plt
import matplotlib as mpl
import xlrd
import warnings
warnings.filterwarnings('ignore')
alt.renderers.enable("png")
alt.data_transformers.disable_max_rows()

data_path = 'c:/Users/s_bea/student30538-w26/ps6-sabtriestech/data/data/external'

# improve graph resolution
import tempfile
from IPython.display import SVG, display, Image
import vl_convert as vlc

def display_altair_png(chart, scale=2):
    """
    Render an Altair chart to a PNG and display it inline.

    Parameters
    ----------
    chart : altair.Chart
        Altair chart object to render.
    scale : int, optional
        Resolution scaling factor for the PNG (default = 2). Use scale=2 for standard slides. Use scale = 3–4 for dense figures or PDF exports.
    """
    png_bytes = vlc.vegalite_to_png(chart.to_dict(), scale=scale)

    # Write to a temporary PNG file and display
    with tempfile.NamedTemporaryFile(suffix=".png") as tmp:
        tmp.write(png_bytes)
        tmp.flush()
        display(Image(filename=tmp.name))
```


```{python}

#| echo: false
#| output: false
#| warning: false

#crime data processing

file_path = 'data/FBI_Crime_Data'

crime_2012 = pd.read_excel(f'{file_path}/2012.xls',
                            skiprows=4, skipfooter=7, index_col=[0]).reset_index() 
crime_2012["Year"] = 2012 
crime_2011 = pd.read_excel(f'{file_path}/2011.xls',
                            skiprows=4, skipfooter=7, index_col=[0]).reset_index() 
crime_2011["Year"] = 2011
crime_2010 = pd.read_excel(f'{file_path}/2010.xls',
                            skiprows=4, skipfooter=7, index_col=[0]).reset_index()
crime_2010["Year"] = 2010 
crime_2009 = pd.read_excel(f'{file_path}/2009.xls',
                            skiprows=4, skipfooter=7, index_col=[0]).reset_index()
crime_2009["Year"] = 2009 
crime_2008 = pd.read_excel(f'{file_path}/2008.xls',
                            skiprows=4, skipfooter=7, index_col=[0]).reset_index()
crime_2008["Year"] = 2008
crime_2007 = pd.read_excel(f'{file_path}/2007.xls',
                            skiprows=4, skipfooter=7, index_col=[0]).reset_index()
crime_2007["Year"] = 2007
crime_2006 = pd.read_excel(f'{file_path}/2006.xls',
                            skiprows=4, skipfooter=8, index_col=[0]).reset_index() 
crime_2006["Year"] = 2006
crime_2005 = pd.read_excel(f'{file_path}/2005.xls',
                            skiprows=4, skipfooter=8, index_col=[0]).reset_index() 
crime_2005["Year"] = 2005

all_sheets = [crime_2012, crime_2011, crime_2010, crime_2009, crime_2008, crime_2007, crime_2006, crime_2005]

# loop over yearly sheets
for s in all_sheets:
    #get rid of line breaks in column headings
    s.columns = s.columns.str.replace('\n', ' ', regex=True)
    #remove footnote from Arson and Rape Column; rename columns that have inconsistent spacing
    s.rename(columns={'Arson1': 'Arson', 'Arson3': 'Arson', 'Arson2': 'Arson', 'Rape1':'Rape',
                       'Metropolitan/Nonmetropolitan': 'County Type', 'Larceny- theft': 'Larceny-theft',
                       'Forcible Rape': 'Rape', 'Forcible  Rape': 'Rape', 'Forcible rape': 'Rape',
                       'Motor  vehicle  theft':'Motor vehicle theft','Motor Vehicle Theft':'Motor vehicle theft',
                       'Murder and  nonnegligent  manslaughter': 'Murder and nonnegligent manslaughter', 
                       'Rape (revised  definition)1': 'Rape (revised definition)1', 
                       'Aggravated  assault': 'Aggravated assault', 'Property  crime': 'Property crime',
                       'Motor  vehicle  theft': 'Motor vehicle theft', 'Violent Crime': 'Violent crime',
                       'Property Crime': 'Property crime', 'Violent  crime':'Violent crime',
                       'Forcible  rape': 'Rape', 'Violent  Crime': 'Violent crime', 
                       'Property  Crime': 'Property crime'}, inplace=True)
    #some states and counties have footnotes at the end that will mean that they won't merge correctly
    s['County'] = s['County'].str.rstrip()
    s['County'] = s['County'].str.replace(r'\s*\d+$', '', regex=True)
    s['State'] = s['State'].str.replace(r'\s*\d+$', '', regex=True)
    #make state titlecase
    s['State'] = s['State'].str.title()

    #split state name from county type
    s[['State', 'County Type']] = s['State'].str.split('-', n=1, expand=True)

#crime data from 2008 has a weird extra column, drop that
crime_2008.drop(columns=['Unnamed: 12'], inplace=True)

# now we concatinate our list of dfs
crime_all = pd.concat(all_sheets, ignore_index=True)

#next so that crime numbers are comparable, we want to scale those by population data. 
#since we don't have numbers for 2011 and 2012 we will use 2010 data for these years. 
pop = pd.read_csv(f'data/Pop_data.csv', encoding='latin1')

pop = pop.drop(columns=['POPESTIMATE2000', 'POPESTIMATE2001', 'POPESTIMATE2002', 'POPESTIMATE2003','POPESTIMATE2004'])

pop['CTYNAME'] = pop['CTYNAME'].str.replace(r" County$", "", regex=True)

#need to rename columns for year and pivot data longer
pop.rename(columns={'POPESTIMATE2005': '2005', 'POPESTIMATE2006': '2006', 
                    'POPESTIMATE2007': '2007', 'POPESTIMATE2008': '2008', 
                    'POPESTIMATE2009': '2009', 'POPESTIMATE2010': '2010'
                    }, inplace=True)
              
#impute 2011 and 2012
pop['2011'] = pop['2010']
pop['2012'] = pop['2010']
pop = pop.drop(columns=['CENSUS2010POP', 'ESTIMATESBASE2000', 
                  'COUNTY', 'STATE', 'DIVISION', 'REGION', 'SUMLEV'])
pop_long = pd.melt(pop, ["STNAME", "CTYNAME"])


pop_long['variable'] = pd.to_numeric(pop_long['variable'], errors='coerce').astype('int64')
crime_all['Year'] = pd.to_numeric(crime_all['Year'], errors='coerce').astype('int64')
pop_long = pop_long.rename(columns={'value': 'Population', 'variable':'Year',
                                    'STNAME': 'State', 'CTYNAME':'County'})

#use regex to fix county names
pop_long['County'] = pop_long['County'].str.replace(r' Parish', '', regex=True)
pop_long['County'] = pop_long['County'].str.replace(r' city', '', regex=True)
pop_long['County'] = pop_long['County'].str.replace(r' City and Borough', '', regex=True)
pop_long['County'] = pop_long['County'].str.replace(r' Borough', '', regex=True)
pop_long['County'] = pop_long['County'].str.replace(r' Census Area', '', regex=True)
pop_long['County'] = pop_long['County'].str.replace(r' Municipality', '', regex=True)
crime_all['County'] = crime_all['County'].str.replace(r" County$", "", regex=True)
crime_all['County'] = crime_all['County'].str.replace(r' County Police Department', '', regex=True)
crime_all['County'] = crime_all['County'].str.replace(r' County Bureau of Police', '', regex=True)
crime_all['County'] = crime_all['County'].str.replace(r' Public Safety', '', regex=True)
crime_all['County'] = crime_all['County'].str.replace(r' Police Department', '', regex=True)
crime_all['County'] = crime_all['County'].str.replace(r'\s*\d+$', '', regex=True)
crime_all['County'] = crime_all['County'].str.replace(r' Unified Police Department', '', regex=True)
crime_all['County'] = crime_all['County'].str.replace(r" Sheriff's Office", '', regex=True)
crime_all['County'] = crime_all['County'].str.replace(r"\d+,", "", regex=True)
crime_all['County'] = crime_all['County'].str.replace(r" County Unified", "", regex=True)
replace_map = {'Dona Ana': 'Doña Ana', 'Du Page': 'DuPage', 'Lac Qui Parle':'Lac qui Parle',
               'La Porte': 'LaPorte', 'Lamoure': 'LaMoure'}
crime_all['County'] = crime_all['County'].replace(replace_map)

crime = crime_all.merge(pop_long, how='inner', 
                        on=['State', 'County', 'Year'], indicator=True)

#create crime rates 
crime['Total crime'] = crime['Violent crime'] + crime['Property crime'] 

crime_col = ['Total crime', 'Violent crime','Murder and nonnegligent manslaughter', 'Rape',
              'Robbery','Aggravated assault', 'Property crime', 'Burglary', 
              'Larceny-theft','Motor vehicle theft', 'Arson']
for c in crime_col:
    crime[f'{c}_rate'] = crime[c] / (crime['Population'] / 100000)

crime = crime.drop(columns=['County Type', '_merge'], errors='ignore')
#groupby to find averages
crime_by_county = crime.groupby(['State', 'County']).mean().reset_index()

#and write out clean dataset
output_path = f'data/derived_data/crime_by_county.csv'
crime_by_county.to_csv(output_path, index=False)
```

```{python}

#| echo: false
#| output: false

#add in county FIPS codes to crime data with a crosswalk
countyfips = pd.read_csv('data\countyfips crosswalk.csv')
countyfips = countyfips[['state_name', 'county', 'countyfips']]

#omit "County" from the end of each county name for matching
countyfips['county'] = countyfips['county'].str.replace(' County', '', regex=False)

#omit "Parish" as well so that Louisiana matches:
countyfips['county'] = countyfips['county'].str.replace(' Parish', '', regex=False)

#in crime data, rename Dona Ana, NM to have no tilde:
crime_by_county.loc[1435, 'County'] = 'Dona Ana'

crime_by_county = crime_by_county.merge(countyfips, 
                                        left_on=['State', 'County'],
                                        right_on=['state_name', 'county'],
                                        how='left',
                                        indicator=True)

assert len(crime_by_county[crime_by_county['_merge'] != 'both']) == 0

crime_by_county = crime_by_county.drop('_merge', axis=1)

```

```{python}
#| echo: false
#| output: false

# QCEW Data

years = list(range(2005, 2013))

dataframes = {}

#read in relevant years in a loop and concatenate
for year in years:

    suffix = f'{year % 100:02d}'
    filename = os.path.join('data\QCEW Files (Raw)', f'allhlcn{suffix}.xlsx')

    if os.path.exists(filename):
        print(f'Reading in file for {year}')

        data = pd.read_excel(filename, sheet_name=0)
        dataframes[year] = data
    else:
        print(f'File not found for year {year}')
        pass

merged_df = pd.concat(dataframes.values(), ignore_index=True)

```


```{python}
#| echo: false

#pull out relevant variables for aggregation
subset_df = merged_df[['Area\nCode', 'Area Type', 'Ownership', 'Industry','Annual Total Wages']]

#we want average industry concentration across our years, so sum raw numbers
grouped_df = subset_df.groupby(['Area\nCode', 'Area Type', 'Ownership', 'Industry'], as_index=False).sum()

#compute wage share for counties
county = grouped_df[grouped_df['Area Type'] == 'County']
county_total = county[county['Ownership'] == 'Total Covered']

county_total = county_total.rename(columns={
    'Annual Total Wages': 'Total County Wages'})

county_total = county_total.drop(columns=['Area Type', 'Ownership', 'Industry'])
county = county.merge(county_total, on='Area\nCode', how='left')

county['Local Wage Share'] = county['Annual Total Wages'] / county['Total County Wages']

#calculate HHI
hhi_data = county[(county['Industry'] != 'Goods-producing') & (county['Industry'] != 'Service-providing')]

hhi_data = hhi_data[hhi_data['Ownership'] != 'Total Covered']

hhi_data = hhi_data[~((hhi_data['Ownership'] == 'Private') & (hhi_data['Industry'] == 'Total, all industries'))]

hhi_group = hhi_data.groupby('Area\nCode', as_index=False).agg({
    'Local Wage Share': lambda x: 1 / (x**2).sum()
})

hhi_group  = hhi_group.rename(columns={
    'Local Wage Share': 'Inverse HHI',
    'Area\nCode': 'countyfips'
})
```

```{python}
#| echo: false
#| output: false

ch_data = pd.read_csv(r'data\chetty_hendren_causal_county_cleaned.csv', encoding='latin-1')
ch_data['County FIPS 2000'] = ch_data['County FIPS 2000'].astype('string')
ch_data['County FIPS 2000'] = ch_data['County FIPS 2000'].str.pad(width=5, side='left', fillchar='0')

#merge with qcew
ch_data = ch_data.merge(hhi_group,
                     how='left',
                     left_on='County FIPS 2000',
                     right_on='countyfips',
                     indicator=True)

#Clifton Forge City fails to merge. It's under 3500 people, and QCEW data does not contain information for counties this small in public data for confidentiality. As it's a single county that doesn't match, drop.

ch_data = ch_data[ch_data['_merge'] == 'both']

ch_data = ch_data.drop('_merge', axis=1)

crime_by_county['countyfips'] = crime_by_county['countyfips'].astype(str)
#crime_by_county = crime_by_county.drop('_merge', axis=1)

full_data = ch_data.merge(crime_by_county,
                     how='inner',
                     left_on='County FIPS 2000',
                     right_on='countyfips',
                     indicator=True)

#drop extraneous columns
full_data = full_data.drop(
    ['_merge', 'countyfips_y', 'State_y', 'countyfips_x', 'State_x', 'County', 'county'],
    axis=1
    )

dashboard_data = full_data[['County FIPS 2000', 'kr26_p25_coef', 'kr26_p75_coef', 'Inverse HHI', 'Median House Price for Below-Median Income Families (Standardized)','Median House Price for Above-Median Income Families (Standardized)', 'Violent crime_rate', 'Property crime_rate']]

dashboard_data.to_csv('data\derived_data\Dashboard Data.csv', index=False)

county_map = gpd.read_file(os.path.join('data\Shapefiles\County\co99_d00.shp'))
county_map = county_map[county_map['STATE'] != '02']

#counstruct countyfips
county_map['GEOID'] = (
    county_map['STATE']
    .astype(str)
    .str.pad(width=2, side='left', fillchar='0') + 
    county_map['COUNTY']
    .astype(str).str.pad(width=3, side='left', fillchar='0')
)

dashboard_shape = county_map.merge(dashboard_data, right_on='County FIPS 2000', left_on='GEOID', how='right')

#for the maps below
full_shape = county_map.merge(full_data, right_on='County FIPS 2000', left_on='GEOID', how='right')

dashboard_shape.to_file('data\derived_data\Dashboard Data with Geography.shp')

```

# Research Question

Our project aimed to explore the social and economic factors that are related to high- and low-mobility counties. In brief: What contributes to areas where children do better than their parents? To do this we brought together Opportunity Insights Data, data from the Quarterly Census on Employment and Wages, FBI data on crime, and U.S. Census data for population and shapefiles.

# Data Approach and Difficulties

Opportunity Insights data was the causal measures of place found in Chetty and Hendren's 2017 papers "The Effect of Neighborhoods on Intergenerational Mobility" I + II, which used data on families that moved to given counties to measure the causal effect of living in a given neighborhood had on children's economic outcomes. The key measure used from this data was "kr26", or the gain in percentile of a child in the national income distribution - if a child grew up in a family in the 25th percentile, and at age 26 is in the 27th percentile, then "kr26" is equal to 2, which represents a gain of 2 percentile points. The dataset also contains rich economic and demographic data for counties, which we take advantage of. It is important to note that these measures were used based on "movers" data from 1996-2012, which we take into consideration when constructing our other measures. We had a sample of about 3100 counties, which excludes counties with not enough movers in this period to construct an index.

We also use QCEW data to construct a measure of industry concentration described below called an "HHI Index." QCEW breaks the total wages and employment in a given county down by industry - broad categories such as "Natural resources and mining," "construction," and "education and health services" - including employment in the federal, state, and local government. We constructed average shares in each industry by summing the total wages in each industry from 2005-2012 (the common coverage period with Chetty Hendren Data and FBI crime data) and dividing by the total wages in a given county from 2005-2012 to get an average measure of wage share across these years.

In terms of data coverage, crime statistics were the limiting factor. Since the Opportunity Insights data focuses on those that moved from 1996-2012, we needed to find some overlapping data for crime in this period. The best source availaible was from county level data from the Crime in the US Report. Data cleaning began by downloading yearly tables, stripping them of unnecessary headers and footnotes, concatenating different years, and harmonizing the names of counties to allow merging with our other data sources. Since the mobility indicators cover a range of years, we averaged crime for the overlapping period and converted it to a rate per 100,000 people to make it more comparable between counties with vastly different populations. There were a few counties that were significant outliers in terms of crime rates. We winsorized these observations to the 95th percentile. Our resulting coverage was approximately 2400 counties where mobility, QCEW, and crime data were all indentified. 

One difficulty we had resulted from the limited coverage in crime data. Since reporting is voluntary, there were entire states missing from our crime data. More importantly, some of these missing states, such as Massachusetts, are near the top of income and education distribution, so the resulting picture of the U.S. that we get may be missing important variation. 

# Resulting Static Plots

The first two static plots are geospatial visualizations of different crime  measures, as we wanted to visualize the discrepancies between regions. Maps for both property and violent crime show a significantly higher crime rates in the Southeast U.S. than in other regions. However, due to methodology behind the mobility data, there was much less visible variation with the exception of a few outliers. For this reason, we decided to not visualize mobility in our dashboard, but to have it as filter to explore other variables. Additionally when we add in mobility data, we loose a significant number of counties in the West and Midwest. The third graph shows Data coverage across both datasets. 

```{python}
#| echo: false
#drop Alaska and Hawaii
county_map = county_map[county_map['STATE'] != '02']
county_map = county_map[county_map['STATE'] != '15']

full_shape = full_shape[full_shape["state_name"]!="Hawaii"]

#want to winsorize property crime to display better
pctile95 = full_data['Property crime_rate'].quantile(0.95)
full_shape["Property crime_rate_winsor"] = np.where(full_shape["Property crime_rate"] > pctile95, 
                                                     pctile95, 
                                                     full_shape["Property crime_rate"]) 
pctile95 = full_shape['Violent crime_rate'].quantile(0.95)
full_shape["Violent crime_rate_winsor"] = np.where(full_shape["Violent crime_rate"] > pctile95, 
                                                     pctile95, 
                                                     full_shape["Violent crime_rate"])

fig, ax = plt.subplots(figsize=(3, 4))

county_map.plot(
    color='lightgrey',   
    ax=ax)

full_shape.plot(
    column='Property crime_rate_winsor',              
    linewidth=0.2,           
    edgecolor='0.5',          
    legend=True,              
    ax=ax,
    zorder=2,
    cmap='magma_r'
    )

cbar_ax = fig.axes[-1]
cbar_ax.set_title('Property Crime Rate\n(per 100,000 residents)', fontsize=10)
ax.set_position([0.03, 0.08, 0.82, 0.85])
cbar_ax.set_position([0.87, 0.25, 0.02, 0.5])

ax.set_title('County-Level Property Crime Rates', fontsize=24)
ax.axis('off')  
ax.set_axis_off()
plt.show()
```

```{python}

#| echo: false

fig, ax = plt.subplots(figsize=(3, 4))

county_map.plot(
    color='lightgrey',   
    ax=ax)

full_shape.plot(
    column='Violent crime_rate_winsor',              
    linewidth=0.2,           
    edgecolor='0.5',          
    legend=True,              
    ax=ax,
    zorder=2,
    cmap='magma_r',
    )

cbar_ax = fig.axes[-1]
cbar_ax.set_title('Violent Crime Rate\n(per 100,000 residents)', fontsize=10)
ax.set_position([0.03, 0.08, 0.82, 0.85])
cbar_ax.set_position([0.87, 0.25, 0.02, 0.5])

ax.set_title('County-Level Violent Crime Rates', fontsize=24)
ax.axis('off')  

ax.set_axis_off()
plt.show()
```


```{python}
#| echo: false
full_sample = full_shape.dropna(subset=['kr26_p25_coef'])
fig, ax = plt.subplots(1, 1, figsize=(3, 4))

county_map.plot(
    color='lightgrey',   
    ax=ax)

full_sample.plot(
    column='kr26_p25_coef',              
    linewidth=0.2,           
    edgecolor='0.5',          
    legend=False,              
    ax=ax,
    zorder=2,
    color="#40248c"
    )

ax.set_title('Data Coverage for Crime and Mobility', fontsize=24)
ax.axis('off')  

ax.set_axis_off()
plt.show()

```


```{python}
#| echo: false
full_sample = full_shape.dropna(subset=['kr26_p25_coef'])
fig, ax = plt.subplots(1, 1, figsize=(3, 4))

county_map.plot(
    color='lightgrey',   
    ax=ax)

full_sample.plot(
    column='kr26_p25_coef',              
    linewidth=0.2,           
    edgecolor='0.5',          
    legend=False,              
    ax=ax,
    zorder=2,
    color="#40248c"
    )

ax.set_title('Data Coverage for Crime and Mobility', fontsize=24)
ax.axis('off')  

ax.set_axis_off()
plt.show()
```

We have a lot of data, so we want to aggregate it up to see patterns. To investigate whether housing prices (the largest expenditure for most families) affects mobility, we divide it into quintiles. Chetty-Hendren's data differentiates between two types of families: families in the 25th percentile of the national income distribution ("below-median income") and families in the 75th percentile of the national income distribution ("above-median income"). We thus take our two housing measures (Median House Price for 1. Above-Median and 2. Below-Median Income Families) and break them into quintiles. We then group by these quintiles and find the mean mobility measure in each quintile. We thus construct the following plot, with the quintiles for families in a given income level on a shared x-axis:

```{python}

#| echo: false
#| output: false

full_data['housing_quint_high'] = pd.qcut(full_data['Median House Price for Above-Median Income Families (Standardized)'], q=5, labels = [1, 2, 3, 4, 5])

full_data['housing_quint_low'] = pd.qcut(full_data['Median House Price for Below-Median Income Families (Standardized)'], q=5, labels = [1, 2, 3, 4, 5])

high_df = full_data.groupby('housing_quint_high').agg({'kr26_p75_coef':
  'mean'}).reset_index()

high_df['Income'] = '75th Percentile'

high_df.rename(columns={'housing_quint_high': 'quintile', 'kr26_p75_coef':
   'mobility'}, inplace=True)

low_df = full_data.groupby('housing_quint_low').agg({'kr26_p25_coef':
   'mean'}).reset_index()
low_df['Income'] = '25th Percentile'
low_df.rename(columns={'housing_quint_low': 'quintile', 'kr26_p25_coef':
  'mobility'}, inplace=True)

combined_df = pd.concat([high_df, low_df])
```

```{python}
#| echo: false

chart = alt.Chart(combined_df).mark_bar().encode(
      x=alt.X('quintile:O', title='Housing Price Quintile'),
      y=alt.Y('mobility:Q', title='Mean Mobility Coefficient (Gain in Percentile)'),
      color=alt.Color('Income:N', scale=alt.Scale(range=['#46327E', '#B63679']), title='Parent Income'),
      xOffset='Income:N'
  ).properties(
      width=400,
      height=300,
      title={
        'text':'Mean Mobility by Housing Prices, Below- and Above-Median Income Families',
        'subtitle': 'As Measured by Child Rank in National Income Distribution at Age 26 '
  })

zero_line_y = alt.Chart(pd.DataFrame({'y': [0]})).mark_rule(
    strokeDash=[5, 5],
    color='black'
).encode(y='y:Q')

final_bar = (chart + zero_line_y).configure_view(clip=False)

final_bar

```

The results are striking. For both levels of income, mobility is concentrated almost entirely in the lowest-housing price quintile, and children who grew up in below-median income families tend to lose rank at age 26 when their housing is in the upper 3 quartiles. At almost every housing level, children who grew up in above-median income families tend to outperform low-income children in mobility (as measured by gain in the national income distribution).

We also want to investigate the relationship between the local labor market and various indicators of mobility. Above, we constructed an HHI (Herfindahl-Hirschman Index) using the wages in a given county to see how concentrated earnings are among different industries. This is calculated by taking our different industry types in QCEW data (manufacturing, education, etc.), computing the share of total wages in a given county that are earned in the industry, and taking the inverse sum of the square of these shares. A value of 1 indicates that wages are entirely concentrated in a given industry, and value of 14 indicates that wages are equally dispersed among each industry. Thus, a higher value indicates more spread out wages and a less concentrated labor market in few industries. Although typically constructed using employment, we used wage concentration because it represents how much money is to be made in a given industry, rather than how many jobs. We thought this a better index for economic mobility.
 

```{python}
#| echo: false
vars = [
      'Gini (Standardized)',
      'Median House Price for Below-Median Income Families (Standardized)',
      'Poverty Rate (Standardized)', 
      'Murder and nonnegligent manslaughter_rate',
      'Income Segregation (Standardized)',
      'Location Affordability of Very Low-Income Individual',
      'School Expenditure per Student (Standardized)',
      'Fraction of Children with Single Mothers (Standardized)',
      'Property crime_rate',
      'Teenage (14-16) Labor Force Participation (Standardized)',
      'Median House Rent for Below-Median Income Families (Standardized)',
      'Unemployment Rate (Standardized)',
      'Fraction of Adults Married (Standardized)'
]

#drop extreme values, as some industries in small counties are missing, leading to extemely high values
wage_data = full_data[full_data['Inverse HHI'] < 10]

outcome = 'Inverse HHI'
results = []

for var in vars:

    clean_data = wage_data[[var, outcome]].dropna()

    #correlation for easy interpretability (in range [-1, 1])
    correlation = clean_data[var].corr(clean_data[outcome])

    #run regression on outcome and HHI to get relationship, p-values
    from scipy import stats
    slope, intercept, r_value, p_value, std_err = stats.linregress(
        clean_data[var],
        clean_data[outcome]
          )

    n = len(clean_data)
    t_critical = stats.t.ppf(0.975, n-2)
    ci_lower = slope - (t_critical * std_err)
    ci_upper = slope + (t_critical * std_err)    

    mean_concentration = clean_data[outcome].mean()

    #get SD of given variable
    var_std = clean_data[var].std()

    #calculate effect of 1 SD increase on HHI, with 95% CIs
    effect_per_sd = slope * var_std
    effect_ci_lower = ci_lower * var_std
    effect_ci_upper = ci_upper * var_std

    #convert to percent
    pct_effect = (effect_per_sd / mean_concentration) * 100
    pct_ci_lower = (effect_ci_lower / mean_concentration) * 100
    pct_ci_upper = (effect_ci_upper / mean_concentration) * 100
    
    results.append({
              'Variable': var,
              'Effect_per_SD': effect_per_sd,
              'Pct_Change': pct_effect,
              'Correlation': correlation,
              'CI_lower': pct_ci_lower,
              'CI_upper': pct_ci_upper,
              'P_value': p_value,
              'Significant': p_value < 0.05
          })

results_df = pd.DataFrame(results)


#clean up variable names for plotting
results_df['Variable'] = results_df['Variable'].str.replace(' (Standardized)', '', regex=False)
results_df['Variable'] = results_df['Variable'].str.replace('(Income adjusted)', '', regex=False)
results_df['Variable'] = results_df['Variable'].str.replace('Teenage (14-16) Labor Force Participation', 'Teen (14-16) LFP', regex=False)
results_df['Variable'] = results_df['Variable'].str.replace(' for Below-Median Income Families', ', Low-Income', regex=False)
results_df['Variable'] = results_df['Variable'].str.replace(' of Very Low-Income Individual', ', Very Low-Income', regex=False)
results_df['Variable'] = results_df['Variable'].str.replace(' and nonnegligent manslaughter_rate', '/Manslaughter Rate')
results_df['Variable'] = results_df['Variable'].str.replace('crime_rate', 'Crime Rate', regex=False)

#convert correlation to string for plotting
results_df['Correlation'] = results_df['Correlation'].astype(str)

#sort by biggest change to avoid "sort=" arg in altair - it breaks text
results_df = results_df.sort_values('Pct_Change', ascending=False)

```

```{python}
#| echo: false
#group indicators by category as suggested by Professor Shi

ordered_vars = [
    #crime statistics
    'Property Crime Rate', 'Murder/Manslaughter Rate', 
    #affordability
    'Location Affordability, Very Low-Income','Median House Rent, Low-Income', 'Median House Price, Low-Income', 'Poverty Rate',
    #inequality measures 
     'Gini', 'Income Segregation', 
    #labor market
    'Teen (14-16) LFP','Unemployment Rate', 
    #social/demographic measures
    'Fraction of Children with Single Mothers', 'Fraction of Adults Married', 'School Expenditure per Student'
    ]


```


```{python}
#| echo: false
#base chart - diamonds showing relationship
points = alt.Chart(results_df).mark_point(
    color="#40248c",
    shape='diamond',
    size=150,
    opacity=1,
    filled=True
    ).encode(
    x=alt.X('Pct_Change:Q',
            title='Change in Wage Dispersion Among Different Industry Classifications (%)',
            scale=alt.Scale(domain=[-4, 6])),  
    y=alt.Y('Variable:O',
            scale=alt.Scale(domain=ordered_vars),
            title='Crime and Mobility Measures')
).properties(height=500, width=800,
             title={
        "text": "Association Between 1 SD Increase of Economic/Crime Measures with Wage Dispersion",
        "subtitle": "With Associated Correlation Coefficients and Confidence Intervals",
        })

#confidence intervals
errorbars = alt.Chart(results_df).mark_errorbar(
    ticks=True,
    size=10,
    color='black'
).encode(
    x=alt.X('CI_lower:Q', title=''),
    x2='CI_upper:Q',
    y=alt.Y('Variable:O',
    scale=alt.Scale(domain=ordered_vars))
)

#correlation coefficent to the right
corr_text = alt.Chart(results_df).mark_text(
).encode(
    x=alt.value(775),
    y=alt.Y('Variable:O',
            scale=alt.Scale(domain=ordered_vars),
            title=None),
    text=alt.Text('Correlation:Q', format='.2f'))

#zero line to delineate positive and negative relationships
zero_line_x = alt.Chart(pd.DataFrame({'x': [0]})).mark_rule(
    strokeDash=[5, 5],
    color='black'
).encode(x='x:Q')

#put layers together
wage_chart = (errorbars + points + zero_line_x + corr_text).configure_view(clip=False)

wage_chart

```

The above shows how various crime, affordability, labor market, and social/demographic variables are related to industry concentration. To standardize, we plot how a 1 SD increase in a given measure changes wage dispersion as a percent increase or decrease. Thus, if a 1 SD increase of a given measure is associated with an increase of inverse HHI from 1 to 2, this corresponds to a 100% increase in wage dispersion (and would thus represent a doubling of the effective number of industries in a county). 

Our analysis favors spreading wages out among industries. Higher crime rates, poverty, unemployment, and inequality (Gini coefficent and income segregation) are associated with more concentrated labor markets, whereas a 1 SD increase in our affordability measures are associated with less concentrated labor markets. It is not, however, a panacea: in less concentrated labor markets, there tend to be more children with single mothers, more teens in the labor force, fewer married adults, and lower school expenditure.

# Streamlit App

Our Streamlit app contains two main components and a number of filters. First, it presents the user with a dropdown box with a number of indicators including crime statistics, HHI for industry concentration, and median housing prices for the 25th and 75th percentiles. Once the user selects an input, the left-hand side of the page presents a spatial representation of different variables, with a tooltip for users to expore values for that indicator. 

The right-hand side of the webpage presents the viewer with a histogram of the selected variable and prints the mean value on the graph. This column has an additional filter that allows users to generate a histogram for counties above or below the median value in terms of mobility. While the mobility coefficients are centered around zero, and don't provide that much information, seeing how housing prices, crime, and industry concentration vary between high and low mobility counties is more interesting. As discussed above, housing prices show a very strong correlation with mobility. 


